apiVersion: v1
kind: Pod
metadata:
  name: sso
spec:
  containers:
    - name: postgres
      image: localhost/postgres
      env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
    - name: redis
      image: docker.io/library/redis:7.4
    - name: sso
      image: localhost/sso
      ports:
        - containerPort: 4001
        - hostPort: 4001
