version: '3'

tasks:
  gen:
    cmds:
      - protoc --go_out=internal/ --go_opt=paths=source_relative --go-grpc_out=internal/ --go-grpc_opt=paths=source_relative proto/*.proto

  lint:
    cmds:
      - golangci-lint run

  test:
    cmds:
      - go test -v ./...
  
  run:
    cmds:
      - go run cmd/main.go -p 4001
