FROM docker.io/library/golang:1.23 as build

WORKDIR /src

COPY ./.. .

RUN ls
RUN go mod tidy
RUN go build -o sso cmd/main.go


FROM docker.io/library/golang:1.23

WORKDIR /src

COPY --from=build /src/sso sso

CMD ["./sso"]
